/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ConnectionFromSQL.VIEW;

import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.BLUE;
import static java.awt.Color.black;
import static java.awt.Color.white;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author mathe
 */
public class InternalChat extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form InternalChat
     */
    public InternalChat() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EnviarBTN = new javax.swing.JButton();
        containerMsg = new javax.swing.JPanel();
        msgOutPane = new javax.swing.JScrollPane();
        msgOut = new javax.swing.JTextArea();
        msgAtendPane = new javax.swing.JScrollPane();
        msgAtend = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputArea = new javax.swing.JTextArea();

        setBorder(null);
        setClosable(true);
        setMaximumSize(new java.awt.Dimension(990, 750));
        setMinimumSize(new java.awt.Dimension(990, 750));
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(990, 750));

        jPanel1.setBackground(new java.awt.Color(20, 26, 38));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnviarBTN.setText("Enviar");
        EnviarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(EnviarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 625, 130, 50));

        containerMsg.setBackground(new java.awt.Color(20, 26, 38));
        containerMsg.setMaximumSize(new java.awt.Dimension(978, 585));
        containerMsg.setMinimumSize(new java.awt.Dimension(978, 585));

        msgOutPane.setBackground(new java.awt.Color(20, 26, 38));
        msgOutPane.setBorder(null);
        msgOutPane.setForeground(new java.awt.Color(20, 26, 38));

        msgOut.setEditable(false);
        msgOut.setBackground(new java.awt.Color(20, 26, 38));
        msgOut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        msgOut.setLineWrap(true);
        msgOut.setTabSize(0);
        msgOutPane.setViewportView(msgOut);

        msgAtendPane.setBackground(new java.awt.Color(20, 26, 38));
        msgAtendPane.setBorder(null);
        msgAtendPane.setForeground(new java.awt.Color(20, 26, 38));

        msgAtend.setEditable(false);
        msgAtend.setBackground(new java.awt.Color(20, 26, 38));
        msgAtend.setColumns(20);
        msgAtend.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        msgAtend.setLineWrap(true);
        msgAtend.setRows(5);
        msgAtend.setBorder(null);
        msgAtendPane.setViewportView(msgAtend);

        javax.swing.GroupLayout containerMsgLayout = new javax.swing.GroupLayout(containerMsg);
        containerMsg.setLayout(containerMsgLayout);
        containerMsgLayout.setHorizontalGroup(
            containerMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerMsgLayout.createSequentialGroup()
                        .addComponent(msgAtendPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerMsgLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(msgOutPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        containerMsgLayout.setVerticalGroup(
            containerMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerMsgLayout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(msgOutPane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgAtendPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(containerMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 579));

        InputArea.setColumns(20);
        InputArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        InputArea.setLineWrap(true);
        InputArea.setRows(5);
        InputArea.setTabSize(1);
        jScrollPane1.setViewportView(InputArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 603, 740, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarBTNActionPerformed
        // TODO add your handling code here:
        String msg = InputArea.getText();
        msgOut.setText(msg);
        msgOut.setBackground(new Color(0xCC, 0xE5, 0xFF));
        msgOut.setForeground(black);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        msgAtend.setBackground(new Color(0xE6, 0xF2, 0xFF));
                        msgAtend.setForeground(Color.BLACK);
                        msgAtend.setText(" Em instantes um colaborador estará à sua disposição para te atender.");
                    }
                });
            }
        });
        timer.setRepeats(false); // Execute apenas uma vez após o atraso
        timer.start();
        LimpaCampo();
    }//GEN-LAST:event_EnviarBTNActionPerformed

    private void LimpaCampo(){
        InputArea.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarBTN;
    private javax.swing.JTextArea InputArea;
    private javax.swing.JPanel containerMsg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgAtend;
    private javax.swing.JScrollPane msgAtendPane;
    private javax.swing.JTextArea msgOut;
    private javax.swing.JScrollPane msgOutPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the enviarBTN
     */
}
